modLoader="lowcodefml"
loaderVersion="43"
license="ARR"
[[mods]]
modId="sob"
version="1.0"
displayName="Smidgeon O' Bliss"
description='''
Food compat. As simple as that.
'''
[[dependencies.sob]]
    modId = "jsonthings"
    mandatory = true
    versionRange = "[0.4.9,)"
    ordering = "NONE"
    side = "BOTH"